// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LatcontrolDebug_msgs.proto

#ifndef PROTOBUF_LatcontrolDebug_5fmsgs_2eproto__INCLUDED
#define PROTOBUF_LatcontrolDebug_5fmsgs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_LatcontrolDebug_5fmsgs_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsLatcontrolDebugImpl();
void InitDefaultsLatcontrolDebug();
inline void InitDefaults() {
  InitDefaultsLatcontrolDebug();
}
}  // namespace protobuf_LatcontrolDebug_5fmsgs_2eproto
namespace LatcontrolDebug_msgs {
class LatcontrolDebug;
class LatcontrolDebugDefaultTypeInternal;
extern LatcontrolDebugDefaultTypeInternal _LatcontrolDebug_default_instance_;
}  // namespace LatcontrolDebug_msgs
namespace LatcontrolDebug_msgs {

// ===================================================================

class LatcontrolDebug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LatcontrolDebug_msgs.LatcontrolDebug) */ {
 public:
  LatcontrolDebug();
  virtual ~LatcontrolDebug();

  LatcontrolDebug(const LatcontrolDebug& from);

  inline LatcontrolDebug& operator=(const LatcontrolDebug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LatcontrolDebug(LatcontrolDebug&& from) noexcept
    : LatcontrolDebug() {
    *this = ::std::move(from);
  }

  inline LatcontrolDebug& operator=(LatcontrolDebug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LatcontrolDebug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LatcontrolDebug* internal_default_instance() {
    return reinterpret_cast<const LatcontrolDebug*>(
               &_LatcontrolDebug_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LatcontrolDebug* other);
  friend void swap(LatcontrolDebug& a, LatcontrolDebug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LatcontrolDebug* New() const PROTOBUF_FINAL { return New(NULL); }

  LatcontrolDebug* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LatcontrolDebug& from);
  void MergeFrom(const LatcontrolDebug& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LatcontrolDebug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float midback = 1;
  void clear_midback();
  static const int kMidbackFieldNumber = 1;
  float midback() const;
  void set_midback(float value);

  // float midfront = 2;
  void clear_midfront();
  static const int kMidfrontFieldNumber = 2;
  float midfront() const;
  void set_midfront(float value);

  // float lat_err_front = 3;
  void clear_lat_err_front();
  static const int kLatErrFrontFieldNumber = 3;
  float lat_err_front() const;
  void set_lat_err_front(float value);

  // float heading = 4;
  void clear_heading();
  static const int kHeadingFieldNumber = 4;
  float heading() const;
  void set_heading(float value);

  // float leftfront = 5;
  void clear_leftfront();
  static const int kLeftfrontFieldNumber = 5;
  float leftfront() const;
  void set_leftfront(float value);

  // float rightfront = 6;
  void clear_rightfront();
  static const int kRightfrontFieldNumber = 6;
  float rightfront() const;
  void set_rightfront(float value);

  // float leftback = 7;
  void clear_leftback();
  static const int kLeftbackFieldNumber = 7;
  float leftback() const;
  void set_leftback(float value);

  // float rightback = 8;
  void clear_rightback();
  static const int kRightbackFieldNumber = 8;
  float rightback() const;
  void set_rightback(float value);

  // float dist_preview = 9;
  void clear_dist_preview();
  static const int kDistPreviewFieldNumber = 9;
  float dist_preview() const;
  void set_dist_preview(float value);

  // float x_previewpoint = 10;
  void clear_x_previewpoint();
  static const int kXPreviewpointFieldNumber = 10;
  float x_previewpoint() const;
  void set_x_previewpoint(float value);

  // float y_previewpoint = 11;
  void clear_y_previewpoint();
  static const int kYPreviewpointFieldNumber = 11;
  float y_previewpoint() const;
  void set_y_previewpoint(float value);

  // float R = 12;
  void clear_r();
  static const int kRFieldNumber = 12;
  float r() const;
  void set_r(float value);

  // float eps_speed = 13;
  void clear_eps_speed();
  static const int kEpsSpeedFieldNumber = 13;
  float eps_speed() const;
  void set_eps_speed(float value);

  // float temp1 = 14;
  void clear_temp1();
  static const int kTemp1FieldNumber = 14;
  float temp1() const;
  void set_temp1(float value);

  // float temp2 = 15;
  void clear_temp2();
  static const int kTemp2FieldNumber = 15;
  float temp2() const;
  void set_temp2(float value);

  // float temp3 = 16;
  void clear_temp3();
  static const int kTemp3FieldNumber = 16;
  float temp3() const;
  void set_temp3(float value);

  // float temp4 = 17;
  void clear_temp4();
  static const int kTemp4FieldNumber = 17;
  float temp4() const;
  void set_temp4(float value);

  // @@protoc_insertion_point(class_scope:LatcontrolDebug_msgs.LatcontrolDebug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float midback_;
  float midfront_;
  float lat_err_front_;
  float heading_;
  float leftfront_;
  float rightfront_;
  float leftback_;
  float rightback_;
  float dist_preview_;
  float x_previewpoint_;
  float y_previewpoint_;
  float r_;
  float eps_speed_;
  float temp1_;
  float temp2_;
  float temp3_;
  float temp4_;
  mutable int _cached_size_;
  friend struct ::protobuf_LatcontrolDebug_5fmsgs_2eproto::TableStruct;
  friend void ::protobuf_LatcontrolDebug_5fmsgs_2eproto::InitDefaultsLatcontrolDebugImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LatcontrolDebug

// float midback = 1;
inline void LatcontrolDebug::clear_midback() {
  midback_ = 0;
}
inline float LatcontrolDebug::midback() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.midback)
  return midback_;
}
inline void LatcontrolDebug::set_midback(float value) {
  
  midback_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.midback)
}

// float midfront = 2;
inline void LatcontrolDebug::clear_midfront() {
  midfront_ = 0;
}
inline float LatcontrolDebug::midfront() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.midfront)
  return midfront_;
}
inline void LatcontrolDebug::set_midfront(float value) {
  
  midfront_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.midfront)
}

// float lat_err_front = 3;
inline void LatcontrolDebug::clear_lat_err_front() {
  lat_err_front_ = 0;
}
inline float LatcontrolDebug::lat_err_front() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.lat_err_front)
  return lat_err_front_;
}
inline void LatcontrolDebug::set_lat_err_front(float value) {
  
  lat_err_front_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.lat_err_front)
}

// float heading = 4;
inline void LatcontrolDebug::clear_heading() {
  heading_ = 0;
}
inline float LatcontrolDebug::heading() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.heading)
  return heading_;
}
inline void LatcontrolDebug::set_heading(float value) {
  
  heading_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.heading)
}

// float leftfront = 5;
inline void LatcontrolDebug::clear_leftfront() {
  leftfront_ = 0;
}
inline float LatcontrolDebug::leftfront() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.leftfront)
  return leftfront_;
}
inline void LatcontrolDebug::set_leftfront(float value) {
  
  leftfront_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.leftfront)
}

// float rightfront = 6;
inline void LatcontrolDebug::clear_rightfront() {
  rightfront_ = 0;
}
inline float LatcontrolDebug::rightfront() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.rightfront)
  return rightfront_;
}
inline void LatcontrolDebug::set_rightfront(float value) {
  
  rightfront_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.rightfront)
}

// float leftback = 7;
inline void LatcontrolDebug::clear_leftback() {
  leftback_ = 0;
}
inline float LatcontrolDebug::leftback() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.leftback)
  return leftback_;
}
inline void LatcontrolDebug::set_leftback(float value) {
  
  leftback_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.leftback)
}

// float rightback = 8;
inline void LatcontrolDebug::clear_rightback() {
  rightback_ = 0;
}
inline float LatcontrolDebug::rightback() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.rightback)
  return rightback_;
}
inline void LatcontrolDebug::set_rightback(float value) {
  
  rightback_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.rightback)
}

// float dist_preview = 9;
inline void LatcontrolDebug::clear_dist_preview() {
  dist_preview_ = 0;
}
inline float LatcontrolDebug::dist_preview() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.dist_preview)
  return dist_preview_;
}
inline void LatcontrolDebug::set_dist_preview(float value) {
  
  dist_preview_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.dist_preview)
}

// float x_previewpoint = 10;
inline void LatcontrolDebug::clear_x_previewpoint() {
  x_previewpoint_ = 0;
}
inline float LatcontrolDebug::x_previewpoint() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.x_previewpoint)
  return x_previewpoint_;
}
inline void LatcontrolDebug::set_x_previewpoint(float value) {
  
  x_previewpoint_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.x_previewpoint)
}

// float y_previewpoint = 11;
inline void LatcontrolDebug::clear_y_previewpoint() {
  y_previewpoint_ = 0;
}
inline float LatcontrolDebug::y_previewpoint() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.y_previewpoint)
  return y_previewpoint_;
}
inline void LatcontrolDebug::set_y_previewpoint(float value) {
  
  y_previewpoint_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.y_previewpoint)
}

// float R = 12;
inline void LatcontrolDebug::clear_r() {
  r_ = 0;
}
inline float LatcontrolDebug::r() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.R)
  return r_;
}
inline void LatcontrolDebug::set_r(float value) {
  
  r_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.R)
}

// float eps_speed = 13;
inline void LatcontrolDebug::clear_eps_speed() {
  eps_speed_ = 0;
}
inline float LatcontrolDebug::eps_speed() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.eps_speed)
  return eps_speed_;
}
inline void LatcontrolDebug::set_eps_speed(float value) {
  
  eps_speed_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.eps_speed)
}

// float temp1 = 14;
inline void LatcontrolDebug::clear_temp1() {
  temp1_ = 0;
}
inline float LatcontrolDebug::temp1() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.temp1)
  return temp1_;
}
inline void LatcontrolDebug::set_temp1(float value) {
  
  temp1_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.temp1)
}

// float temp2 = 15;
inline void LatcontrolDebug::clear_temp2() {
  temp2_ = 0;
}
inline float LatcontrolDebug::temp2() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.temp2)
  return temp2_;
}
inline void LatcontrolDebug::set_temp2(float value) {
  
  temp2_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.temp2)
}

// float temp3 = 16;
inline void LatcontrolDebug::clear_temp3() {
  temp3_ = 0;
}
inline float LatcontrolDebug::temp3() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.temp3)
  return temp3_;
}
inline void LatcontrolDebug::set_temp3(float value) {
  
  temp3_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.temp3)
}

// float temp4 = 17;
inline void LatcontrolDebug::clear_temp4() {
  temp4_ = 0;
}
inline float LatcontrolDebug::temp4() const {
  // @@protoc_insertion_point(field_get:LatcontrolDebug_msgs.LatcontrolDebug.temp4)
  return temp4_;
}
inline void LatcontrolDebug::set_temp4(float value) {
  
  temp4_ = value;
  // @@protoc_insertion_point(field_set:LatcontrolDebug_msgs.LatcontrolDebug.temp4)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace LatcontrolDebug_msgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LatcontrolDebug_5fmsgs_2eproto__INCLUDED
