#include "decision_gflags.h"

DEFINE_bool(specific_pull_over_enable, true, "take pullover as scenario");
DEFINE_bool(pull_over_boundary_enable, true, "offset while pull over");
DEFINE_bool(congestion_enable, true, "abandon intention when congestion");
DEFINE_bool(pedal_enable, true, "recieve pedal signal to ignore safety");
DEFINE_bool(gap_enable, false, "choose specific gap for lc");
DEFINE_bool(mission_lc_stop_enable, true, "set last mission lc stop point");
DEFINE_double(dis_to_switch_junction, 30.0, "distance to enter junction scenario");
DEFINE_double(pull_over_dis, 60.0, "distance to enter pullover scenario");
DEFINE_double(base_lc_dis, 25.0, "comfort lane changing distance while still");
DEFINE_double(expected_lc_dis, 300.0, "free distance to excute lane changing");
DEFINE_double(turnlight_dis, 50.0, "distance forward to open turnlight");
DEFINE_int32(decision_frame, 3, "frame forward to get option");
DEFINE_int32(start_yield_frame, 0, "frame to check dynamic objects before start");
DEFINE_double(stable_time, 3.0, "stable time after lc");
DEFINE_double(stable_l, 1.0, "stable l after lc");
DEFINE_double(stable_angle, 5.0, "stable angle after lc");
DEFINE_bool(junction_conflict_enable, true, "set stop point for junction conflict");
DEFINE_double(crosswalk_speed_limit, 3.0, "speed limit while someone near crosswalk");
DEFINE_double(min_yield_dis, 3.0, "safety distance while searching st map");
DEFINE_double(max_acc, 1.5, "max acceleration for stmap decision");
DEFINE_double(max_dec, -2.5, "max deceleration for stmap decision");
DEFINE_bool(decision_stmap, false, "update stmap enable");
DEFINE_double(yellow_t,2.0, "yellow time to stop");
DEFINE_double(blink_t, 3.0, "blink green light time");
DEFINE_double(delta_t, 0.5, "hysteretic time for trafficlight");
DEFINE_double(ready_ego_angle, 10.0, "ego angle threshold to ready");
DEFINE_double(ready_steer_angle, 90.0, "steer angle threshold to ready");
DEFINE_int32(turnlight_frame, 1, "frame forward to open turnlight");
DEFINE_bool(enable_dynamic_sl_generation, false, "whether enable dynamic-sl genration");
DEFINE_bool(enable_dynamic_sl_debug_plot, false, "whether enable dynamic-sl debug on screen");
DEFINE_int32(mission_lc_blocked_frame,100, "time limit for global path replan when mission lc but blocked");
DEFINE_int32(cruise_blocked_frame, 10, "time limit for global path replan when cruise but blocked");
DEFINE_bool(green_wave_enable, false, "whether enable green wave speed alert");
DEFINE_double(green_wave_acc, 1.5, "green wave speed guiad acc");
DEFINE_double(green_wave_dec, -2, "green wave speed guiad dec");
DEFINE_double(green_wave_lowest_spd, 2, "green wave speed guiad lowest speed m/s");
DEFINE_double(green_wave_highest_spd, 10, "green wave speed guiad highest speed m/s");
