// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_stop_sign.proto

#ifndef PROTOBUF_map_5fstop_5fsign_2eproto__INCLUDED
#define PROTOBUF_map_5fstop_5fsign_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "map_id.pb.h"
#include "map_geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_map_5fstop_5fsign_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStopSignImpl();
void InitDefaultsStopSign();
inline void InitDefaults() {
  InitDefaultsStopSign();
}
}  // namespace protobuf_map_5fstop_5fsign_2eproto
namespace acu {
namespace hdmap {
class StopSign;
class StopSignDefaultTypeInternal;
extern StopSignDefaultTypeInternal _StopSign_default_instance_;
}  // namespace hdmap
}  // namespace acu
namespace acu {
namespace hdmap {

enum StopSign_StopType {
  StopSign_StopType_UNKNOWN = 0,
  StopSign_StopType_ONE_WAY = 1,
  StopSign_StopType_TWO_WAY = 2,
  StopSign_StopType_THREE_WAY = 3,
  StopSign_StopType_FOUR_WAY = 4,
  StopSign_StopType_ALL_WAY = 5
};
bool StopSign_StopType_IsValid(int value);
const StopSign_StopType StopSign_StopType_StopType_MIN = StopSign_StopType_UNKNOWN;
const StopSign_StopType StopSign_StopType_StopType_MAX = StopSign_StopType_ALL_WAY;
const int StopSign_StopType_StopType_ARRAYSIZE = StopSign_StopType_StopType_MAX + 1;

const ::google::protobuf::EnumDescriptor* StopSign_StopType_descriptor();
inline const ::std::string& StopSign_StopType_Name(StopSign_StopType value) {
  return ::google::protobuf::internal::NameOfEnum(
    StopSign_StopType_descriptor(), value);
}
inline bool StopSign_StopType_Parse(
    const ::std::string& name, StopSign_StopType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StopSign_StopType>(
    StopSign_StopType_descriptor(), name, value);
}
// ===================================================================

class StopSign : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:acu.hdmap.StopSign) */ {
 public:
  StopSign();
  virtual ~StopSign();

  StopSign(const StopSign& from);

  inline StopSign& operator=(const StopSign& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StopSign(StopSign&& from) noexcept
    : StopSign() {
    *this = ::std::move(from);
  }

  inline StopSign& operator=(StopSign&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopSign& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopSign* internal_default_instance() {
    return reinterpret_cast<const StopSign*>(
               &_StopSign_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StopSign* other);
  friend void swap(StopSign& a, StopSign& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StopSign* New() const PROTOBUF_FINAL { return New(NULL); }

  StopSign* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StopSign& from);
  void MergeFrom(const StopSign& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StopSign* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef StopSign_StopType StopType;
  static const StopType UNKNOWN =
    StopSign_StopType_UNKNOWN;
  static const StopType ONE_WAY =
    StopSign_StopType_ONE_WAY;
  static const StopType TWO_WAY =
    StopSign_StopType_TWO_WAY;
  static const StopType THREE_WAY =
    StopSign_StopType_THREE_WAY;
  static const StopType FOUR_WAY =
    StopSign_StopType_FOUR_WAY;
  static const StopType ALL_WAY =
    StopSign_StopType_ALL_WAY;
  static inline bool StopType_IsValid(int value) {
    return StopSign_StopType_IsValid(value);
  }
  static const StopType StopType_MIN =
    StopSign_StopType_StopType_MIN;
  static const StopType StopType_MAX =
    StopSign_StopType_StopType_MAX;
  static const int StopType_ARRAYSIZE =
    StopSign_StopType_StopType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StopType_descriptor() {
    return StopSign_StopType_descriptor();
  }
  static inline const ::std::string& StopType_Name(StopType value) {
    return StopSign_StopType_Name(value);
  }
  static inline bool StopType_Parse(const ::std::string& name,
      StopType* value) {
    return StopSign_StopType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .acu.hdmap.Curve stop_line = 2;
  int stop_line_size() const;
  void clear_stop_line();
  static const int kStopLineFieldNumber = 2;
  const ::acu::hdmap::Curve& stop_line(int index) const;
  ::acu::hdmap::Curve* mutable_stop_line(int index);
  ::acu::hdmap::Curve* add_stop_line();
  ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Curve >*
      mutable_stop_line();
  const ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Curve >&
      stop_line() const;

  // repeated .acu.hdmap.Id overlap_id = 3;
  int overlap_id_size() const;
  void clear_overlap_id();
  static const int kOverlapIdFieldNumber = 3;
  const ::acu::hdmap::Id& overlap_id(int index) const;
  ::acu::hdmap::Id* mutable_overlap_id(int index);
  ::acu::hdmap::Id* add_overlap_id();
  ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Id >*
      mutable_overlap_id();
  const ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Id >&
      overlap_id() const;

  // optional .acu.hdmap.Id id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::acu::hdmap::Id& id() const;
  ::acu::hdmap::Id* release_id();
  ::acu::hdmap::Id* mutable_id();
  void set_allocated_id(::acu::hdmap::Id* id);

  // optional .acu.hdmap.StopSign.StopType type = 4;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::acu::hdmap::StopSign_StopType type() const;
  void set_type(::acu::hdmap::StopSign_StopType value);

  // @@protoc_insertion_point(class_scope:acu.hdmap.StopSign)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Curve > stop_line_;
  ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Id > overlap_id_;
  ::acu::hdmap::Id* id_;
  int type_;
  friend struct ::protobuf_map_5fstop_5fsign_2eproto::TableStruct;
  friend void ::protobuf_map_5fstop_5fsign_2eproto::InitDefaultsStopSignImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StopSign

// optional .acu.hdmap.Id id = 1;
inline bool StopSign::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StopSign::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StopSign::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::acu::hdmap::Id& StopSign::id() const {
  const ::acu::hdmap::Id* p = id_;
  // @@protoc_insertion_point(field_get:acu.hdmap.StopSign.id)
  return p != NULL ? *p : *reinterpret_cast<const ::acu::hdmap::Id*>(
      &::acu::hdmap::_Id_default_instance_);
}
inline ::acu::hdmap::Id* StopSign::release_id() {
  // @@protoc_insertion_point(field_release:acu.hdmap.StopSign.id)
  clear_has_id();
  ::acu::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::acu::hdmap::Id* StopSign::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    id_ = new ::acu::hdmap::Id;
  }
  // @@protoc_insertion_point(field_mutable:acu.hdmap.StopSign.id)
  return id_;
}
inline void StopSign::set_allocated_id(::acu::hdmap::Id* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    set_has_id();
  } else {
    clear_has_id();
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:acu.hdmap.StopSign.id)
}

// repeated .acu.hdmap.Curve stop_line = 2;
inline int StopSign::stop_line_size() const {
  return stop_line_.size();
}
inline const ::acu::hdmap::Curve& StopSign::stop_line(int index) const {
  // @@protoc_insertion_point(field_get:acu.hdmap.StopSign.stop_line)
  return stop_line_.Get(index);
}
inline ::acu::hdmap::Curve* StopSign::mutable_stop_line(int index) {
  // @@protoc_insertion_point(field_mutable:acu.hdmap.StopSign.stop_line)
  return stop_line_.Mutable(index);
}
inline ::acu::hdmap::Curve* StopSign::add_stop_line() {
  // @@protoc_insertion_point(field_add:acu.hdmap.StopSign.stop_line)
  return stop_line_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Curve >*
StopSign::mutable_stop_line() {
  // @@protoc_insertion_point(field_mutable_list:acu.hdmap.StopSign.stop_line)
  return &stop_line_;
}
inline const ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Curve >&
StopSign::stop_line() const {
  // @@protoc_insertion_point(field_list:acu.hdmap.StopSign.stop_line)
  return stop_line_;
}

// repeated .acu.hdmap.Id overlap_id = 3;
inline int StopSign::overlap_id_size() const {
  return overlap_id_.size();
}
inline const ::acu::hdmap::Id& StopSign::overlap_id(int index) const {
  // @@protoc_insertion_point(field_get:acu.hdmap.StopSign.overlap_id)
  return overlap_id_.Get(index);
}
inline ::acu::hdmap::Id* StopSign::mutable_overlap_id(int index) {
  // @@protoc_insertion_point(field_mutable:acu.hdmap.StopSign.overlap_id)
  return overlap_id_.Mutable(index);
}
inline ::acu::hdmap::Id* StopSign::add_overlap_id() {
  // @@protoc_insertion_point(field_add:acu.hdmap.StopSign.overlap_id)
  return overlap_id_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Id >*
StopSign::mutable_overlap_id() {
  // @@protoc_insertion_point(field_mutable_list:acu.hdmap.StopSign.overlap_id)
  return &overlap_id_;
}
inline const ::google::protobuf::RepeatedPtrField< ::acu::hdmap::Id >&
StopSign::overlap_id() const {
  // @@protoc_insertion_point(field_list:acu.hdmap.StopSign.overlap_id)
  return overlap_id_;
}

// optional .acu.hdmap.StopSign.StopType type = 4;
inline bool StopSign::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StopSign::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StopSign::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StopSign::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::acu::hdmap::StopSign_StopType StopSign::type() const {
  // @@protoc_insertion_point(field_get:acu.hdmap.StopSign.type)
  return static_cast< ::acu::hdmap::StopSign_StopType >(type_);
}
inline void StopSign::set_type(::acu::hdmap::StopSign_StopType value) {
  assert(::acu::hdmap::StopSign_StopType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:acu.hdmap.StopSign.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap
}  // namespace acu

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::acu::hdmap::StopSign_StopType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::acu::hdmap::StopSign_StopType>() {
  return ::acu::hdmap::StopSign_StopType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_map_5fstop_5fsign_2eproto__INCLUDED
